/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// console.log(process.env.AWS_APPSYNC_AUTHENTICATIONTYPE);

const awsmobile = {
  aws_project_region: process.env.REACT_APP_AWS_REGION,
  aws_appsync_graphqlEndpoint:
    process.env.REACT_APP_AWS_APPSYNC_GRAPHQLENDPOINT,
  aws_appsync_region: process.env.REACT_APP_AWS_REGION,
  aws_appsync_authenticationType:
    process.env.REACT_APP_AWS_APPSYNC_AUTHENTICATIONTYPE,
  aws_appsync_apiKey: process.env.REACT_APP_AWS_APPSYNC_APIKEY,
};
// const awsmobile = {
//     "aws_project_region": "ap-northeast-1",
//     "aws_appsync_graphqlEndpoint": "https://pc4epbmkibcqlbo2y7gjs6u56a.appsync-api.ap-northeast-1.amazonaws.com/graphql",
//     "aws_appsync_region": "ap-northeast-1",
//     "aws_appsync_authenticationType": "API_KEY",
//     "aws_appsync_apiKey": "da2-h32x2eikrje3xjkem7vhvws5y4"
// };

export default awsmobile;
