name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        run: |
          touch .env
          echo -e "REACT_APP_AWS_REGION="${{ secrets.REACT_APP_AWS_REGION }}"
          REACT_APP_AWS_APPSYNC_GRAPHQLENDPOINT="${{ secrets.REACT_APP_AWS_APPSYNC_GRAPHQLENDPOINT }}"
          REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID="${{ secrets.REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID }}"
          REACT_APP_AWS_USER_POOLS_ID="${{ secrets.REACT_APP_AWS_USER_POOLS_ID }}"
          REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID="${{ secrets.REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID }}"
          REACT_APP_OAUTH=${{ secrets.REACT_APP_OAUTH }}
          REACT_APP_AWS_COGNITO_USERNAME_ATTRIBUTES="${{ secrets.REACT_APP_AWS_COGNITO_USERNAME_ATTRIBUTES }}"
          REACT_APP_AWS_COGNITO_SOCIAL_PROVIDERS="${{ secrets.REACT_APP_AWS_COGNITO_SOCIAL_PROVIDERS }}"
          REACT_APP_AWS_COGNITO_SIGNUP_ATTRIBUTES="${{ secrets.REACT_APP_AWS_COGNITO_SIGNUP_ATTRIBUTES }}"
          REACT_APP_AWS_COGNITO_MFA_CONFIGURATION="${{ secrets.REACT_APP_AWS_COGNITO_MFA_CONFIGURATION }}"
          REACT_APP_AWS_COGNITO_MFA_TYPES="${{ secrets.REACT_APP_AWS_COGNITO_MFA_TYPES }}"
          REACT_APP_PASSWORDPOLICYMINLENGTH=${{ secrets.REACT_APP_PASSWORDPOLICYMINLENGTH }}
          REACT_APP_PASSWORDPOLICYCHARACTERS="${{ secrets.REACT_APP_PASSWORDPOLICYCHARACTERS }}"
          REACT_APP_AWS_COGNITO_VERIFICATION_MECHANISMS="${{ secrets.REACT_APP_AWS_COGNITO_VERIFICATION_MECHANISMS }}"" >> .env
      - name: envCheck
        run: |
          cat .env
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
