name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        run: |
          touch .env
          echo -e "REACT_APP_AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }}\n
                    REACT_APP_AWS_APPSYNC_AUTHENTICATIONTYPE=${{ secrets.REACT_APP_AWS_APPSYNC_AUTHENTICATIONTYPE }}\n
                    REACT_APP_AWS_APPSYNC_GRAPHQLENDPOINT=${{ secrets.REACT_APP_AWS_APPSYNC_GRAPHQLENDPOINT }}\n
                    REACT_APP_AWS_APPSYNC_APIKEY=${{ secrets.REACT_APP_AWS_APPSYNC_APIKEY }}" >> .env
      - name: envCheck
        run: |
          cat .env
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
