name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
		              command-prefix: yarn dlx
          start: yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome
          headless: true